<?xml version="1.0" encoding="UTF-8"?>
<BWSharedResource>
    <name>MSG5101.cpy</name>
    <resourceType>ae.shared.CCBSchemaResource</resourceType>
    <config>
        <version>3.4.0</version>
        <fixedFormat>true</fixedFormat>
        <encoding>ASCII</encoding>
        <copybookType>COBOL</copybookType>
        <float>ieee</float>
        <floatSet>true</floatSet>
        <modified>true</modified>
        <dayMonth>Day/month</dayMonth>
        <dateFormat>YYYYXXXX</dateFormat>
        <legacyAlign>false</legacyAlign>
        <metadataVersion>1</metadataVersion>
        <copybook>      *                                                                         &#xD;
       01  STC200-SEGMENT-IO-AREA.                                              &#xD;
           05  STC200-MSG.                                                      &#xD;
               10  STC200-MSG-SEQ-NUM  PIC 9(04).                    &#xD;
               10  STC200-MSG-KEY-VALUE.                                        &#xD;
                   15  STC200-MSG-TYPE PIC X(04).                               &#xD;
                    15  STC200-MSG-ID.                                           &#xD;
                       20  STC200-MSG-DATE.                                     &#xD;
                           25  STC200-MSG-YY PIC 9(02).                         &#xD;
                           25  STC200-MSG-MM PIC 9(02).                         &#xD;
                           25  STC200-MSG-DD PIC 9(02).                         &#xD;
                       20  STC200-MSG-TIME.                                     &#xD;
                           25  STC200-MSG-HOURS PIC 9(02).                      &#xD;
                           25  STC200-MSG-MINUTES PIC 9(02).                    &#xD;
                           25  STC200-MSG-SECONDS PIC 9(02).                    &#xD;
                           25  STC200-MSG-DECIMAL PIC X(01) VALUE '.'.          &#xD;
                           25  STC200-MSG-MILLI-SEC PIC 9(03).                  &#xD;
               10  STC200-MSG-SEQ-STUFFER PIC 9(04).                 &#xD;
               10  STC200-MSG-CARRIER-CODE PIC X(03).                           &#xD;
               10  STC200-MSG-PROGRAM-ID PIC X(08).                        &#xD; 
     02  CSOC-PAIRING-RECORD-WORK-AREA.                                       &#xD;
           05  CSOC-PAIRING-RECORD-COUNTS.                                      &#xD;
               10  CSOC225-GEN-PRG-COUNT PIC 9(02).                             &#xD;
               10  CSOC226-POS-COUNT   PIC 9(02).                               &#xD;
               10  CSOC227-OVR-COUNT   PIC 9(02).                               &#xD;
               10  CSOC228-LEG-COUNT   PIC 9(02).                               &#xD;
               10  CSOC229-DTY-COUNT   PIC 9(02).                               &#xD;
           05  CSOC225-GENERAL-PAIRING-DATA.                                    &#xD;
               10  CSOC225-ACTION-CODE PIC X(01).                               &#xD;
                   88  CSOC225-ADD VALUE 'A'.                                   &#xD;
                   88  CSOC225-CHANGE VALUE 'C'.                                &#xD;
                   88  CSOC225-DELETE VALUE 'D'.                                &#xD;
               10  CSOC225-PRNG-KEY.                                            &#xD;
                   15  CSOC225-PRNG-CARRIER PIC X(03).                          &#xD;
                   15  CSOC225-PRNG-CLASS PIC X(01).                            &#xD;
                   15  CSOC225-PRNG-NUM PIC X(06).                              &#xD;
                   15  CSOC225-PRNG-DATE PIC X(08).                             &#xD;
               10  CSOC225-PRNG-END-DATE PIC X(08).                             &#xD;
               10  CSOC225-PRNG-STATUS-IND PIC X(01).                           &#xD;
               10  CSOC225-PRNG-CANCEL-IND PIC X(01).                           &#xD;
               10  CSOC225-EFF-FROM-ZULU PIC X(08).                             &#xD;
               10  CSOC225-EFF-TO-ZULU PIC X(08).                               &#xD;
               10  CSOC225-FREQ        PIC X(04).                               &#xD;
               10  CSOC225-DOM-INTL-IND PIC X(01).                              &#xD;
               10  CSOC225-COMMENTS    PIC X(234).                              &#xD;
               10  CSOC225-PAIRING-TOTALS.                                      &#xD;
                   15  CSOC225-SCHED-FLT-TIME.                                  &#xD;
                       20  CSOC225-SCH-FLT-HRS PIC X(03).                       &#xD;
                       20  CSOC225-SCH-FLT-MM PIC X(02).                        &#xD;
                   15  CSOC225-ACTUAL-FLT-TIME.                                 &#xD;
                       20  CSOC225-ACT-FLT-HRS PIC X(03).                       &#xD;
                       20  CSOC225-ACT-FLT-MM PIC X(02).                        &#xD;
                   15  CSOC225-SCHED-DH-TIME.                                   &#xD;
                       20  CSOC225-SCH-DH-HRS PIC X(03).                        &#xD;
                       20  CSOC225-SCH-DH-MM PIC X(02).                         &#xD;
                   15  CSOC225-ACTUAL-DH-TIME.                                  &#xD;
                       20  CSOC225-ACT-DH-HRS PIC X(03).                        &#xD;
                       20  CSOC225-ACT-DH-MM PIC X(02).                         &#xD;
                   15  CSOC225-SCHED-GUAR-TIME.                                 &#xD;
                       20  CSOC225-SCH-GUAR-HRS PIC X(03).                      &#xD;
                       20  CSOC225-SCH-GUAR-MM PIC X(02).                       &#xD;
                   15  CSOC225-ACTUAL-GUAR-TIME.                                &#xD;
                       20  CSOC225-ACT-GUAR-HRS PIC X(03).                      &#xD;
                       20  CSOC225-ACT-GUAR-MM PIC X(02).                       &#xD;
                   15  CSOC225-SCHED-PAY-TIME.                                  &#xD;
                       20  CSOC225-SCH-PAY-HRS PIC X(03).                       &#xD;
                       20  CSOC225-SCH-PAY-MM PIC X(02).                        &#xD;
                   15  CSOC225-ACTUAL-PAY-TIME.                                 &#xD;
                       20  CSOC225-ACT-PAY-HRS PIC X(03).                       &#xD;
                       20  CSOC225-ACT-PAY-MM PIC X(02).                        &#xD;
                   15  CSOC225-SCHED-TAFB.                                      &#xD;
                       20  CSOC225-SCH-TAFB-HRS PIC X(03).                      &#xD;
                       20  CSOC225-SCH-TAFB-MM PIC X(02).                       &#xD;
                   15  CSOC225-ACTUAL-TAFB.                                     &#xD;
                       20  CSOC225-ACT-TAFB-HRS PIC X(03).                      &#xD;
                       20  CSOC225-ACT-TAFB-MM PIC X(02).                       &#xD;
               10  CSOC225-UPDATE-DATA.                                         &#xD;
                   15  CSOC225-UPDATE-EMP-NO PIC X(10).                         &#xD;
                   15  CSOC225-UPDATE-DATE PIC X(08).                           &#xD;
                   15  CSOC225-UPDATE-TIME PIC X(06).                           &#xD;
           05  CSOC226-PAIRING-POS-WORK-AREA.                                   &#xD;
               10  CSOC226-POSITIONS OCCURS 0 TO 24 TIMES                       &#xD;
               DEPENDING ON CSOC226-POS-COUNT INDEXED BY CSOC226-INDEX.         &#xD;
                   15  CSOC226-POS-ASSGN-POS PIC X(04).                         &#xD;
                   15  CSOC226-POS-STATUS PIC X(01).                            &#xD;
                   15  CSOC226-POS-RSRV-IND PIC X(01).                          &#xD;
                   15  CSOC226-POS-EMP-ID PIC X(10).                            &#xD;
                   15  CSOC226-POS-EMP-NAME.                                    &#xD;
                       20  CSOC226-POS-EMP-FIRST-NAME PIC X(15).                &#xD;
                       20  CSOC226-POS-EMP-MID-INIT PIC X(01).                  &#xD;
                       20  CSOC226-POS-EMP-LAST-NAME PIC X(15).                 &#xD;
           05  CSOC227-PAIRING-POS-OVR-AREA.                                    &#xD;
RH1103         10  CSOC227-POS-OVR-DATA OCCURS 0 TO 50 TIMES                    &#xD;
               DEPENDING ON CSOC227-OVR-COUNT INDEXED BY CSOC227-INDEX.         &#xD;
KV9609             15  CSOC227-POS-OVR-ACTION-CODE PIC X(01).                   &#xD;
                   15  CSOC227-POS-OVR-ASSGN-POS PIC X(04).                     &#xD;
                   15  CSOC227-POS-OVR-SEQ-NUM PIC X(03).                       &#xD;
                   15  CSOC227-POS-OVR-POS PIC X(04).                           &#xD;
           05  CSOC228-PAIRING-LEG-AREA.                                        &#xD;
KV1103         10  CSOC228-LEG-DATA OCCURS 0 TO 50 TIMES                        &#xD;
               DEPENDING ON CSOC228-LEG-COUNT INDEXED BY CSOC228-INDEX.         &#xD;
                   15  CSOC228-SEQ-NUM PIC X(03).                               &#xD;
                   15  CSOC228-SCH-DPT-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC228-SCH-DPT-TIME-ZULU PIC X(04).                     &#xD;
                   15  CSOC228-CARRIER PIC X(03).                               &#xD;
                   15  CSOC228-FLT-NUM PIC X(04).                               &#xD;
                   15  CSOC228-DPT-CITY PIC X(03).                              &#xD;
                   15  CSOC228-ARR-CITY PIC X(03).                              &#xD;
                   15  CSOC228-EQUIPMENT-CODE PIC X(03).                        &#xD;
                   15  CSOC228-FLIGHT-LEG-STATUS PIC X(02).                     &#xD;
                   15  CSOC228-ROB-IND PIC X(01).                               &#xD;
                   15  CSOC228-LEG-DOM-INTL-IND PIC X(01).                      &#xD;
                   15  CSOC228-DH-IND  PIC X(01).                               &#xD;
                   15  CSOC228-DH-CARRIER PIC X(03).                            &#xD;
                   15  CSOC228-RECORD-LOCATOR-PNR PIC X(06).                    &#xD;
                   15  CSOC228-SCH-AUG-CNT PIC X(01).                           &#xD;
                   15  CSOC228-ACT-AUG-CNT PIC X(01).                           &#xD;
                   15  CSOC228-SCH-ARR-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC228-SCH-ARR-TIME-ZULU PIC X(04).                     &#xD;
                   15  CSOC228-EST-DPT-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC228-EST-DPT-TIME-ZULU PIC X(04).                     &#xD;
                   15  CSOC228-EST-ARR-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC228-EST-ARR-TIME-ZULU PIC X(04).                     &#xD;
                   15  CSOC228-ACT-DPT-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC228-ACT-DPT-TIME-ZULU PIC X(04).                     &#xD;
                   15  CSOC228-ACT-ARR-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC228-ACT-ARR-TIME-ZULU PIC X(04).                     &#xD;
                   15  CSOC228-TAIL-NUMBER PIC X(04).                           &#xD;
           05  CSOC229-DUTY-AREA.                                               &#xD;
KV1103         10  CSOC229-DUTY-DATA OCCURS 0 TO 20 TIMES                       &#xD;
               DEPENDING ON CSOC229-DTY-COUNT INDEXED BY CSOC229-INDEX.         &#xD;
                   15  CSOC229-DTY-SEQ-NUM PIC X(03).                           &#xD;
                   15  CSOC229-DTY-REST-TYPE-1 PIC X(02).                       &#xD;
                   15  CSOC229-DTY-REST-TYPE-2 PIC X(02).                       &#xD;
                   15  CSOC229-DTY-DUTY-NUM PIC X(04).                          &#xD;
                   15  CSOC229-SCH-RPT-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC229-SCH-BRF-TIME-ZULU PIC X(04).                     &#xD;
                   15  CSOC229-ACT-RPT-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC229-ACT-BRF-TIME-ZULU PIC X(04).                     &#xD;
                   15  CSOC229-SCH-END-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC229-SCH-DBRF-TIME-ZULU PIC X(04).                    &#xD;
                   15  CSOC229-ACT-END-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC229-ACT-DBRF-TIME-ZULU PIC X(04).                    &#xD;
                   15  CSOC229-DTY-HTL-CODE PIC X(03).                          &#xD;
                   15  CSOC229-SCH-DTY-AUGMENT-CNT PIC X(01).                   &#xD;
                   15  CSOC229-ACT-DTY-AUGMENT-CNT PIC X(01).                   &#xD;
                   15  CSOC229-SCH-DTY-FLT-TIME.                                &#xD;
                       20  CSOC229-SCH-DTY-FLT-HRS PIC X(03).                   &#xD;
                       20  CSOC229-SCH-DTY-FLT-MM PIC X(02).                    &#xD;
                   15  CSOC229-ACT-DTY-FLT-TIME.                                &#xD;
                       20  CSOC229-ACT-DTY-FLT-HRS PIC X(03).                   &#xD;
                       20  CSOC229-ACT-DTY-FLT-MM PIC X(02).                    &#xD;
                   15  CSOC229-SCH-DTY-DUTY-TIME.                               &#xD;
                       20  CSOC229-SCH-DTY-DUTY-HRS PIC X(03).                  &#xD;
                       20  CSOC229-SCH-DTY-DUTY-MM PIC X(02).                   &#xD;
                   15  CSOC229-ACT-DTY-DUTY-TIME.                               &#xD;
                       20  CSOC229-ACT-DTY-DUTY-HRS PIC X(03).                  &#xD;
                       20  CSOC229-ACT-DTY-DUTY-MM PIC X(02).                   &#xD;
                   15  CSOC229-SCH-DTY-LAYOVER-TIME.                            &#xD;
                       20  CSOC229-SCH-DTY-LAYOVER-HRS PIC X(03).               &#xD;
                       20  CSOC229-SCH-DTY-LAYOVER-MM PIC X(02).                &#xD;
                   15  CSOC229-ACT-DTY-LAYOVER-TIME.                            &#xD;
                       20  CSOC229-ACT-DTY-LAYOVER-HRS PIC X(03).               &#xD;
                       20  CSOC229-ACT-DTY-LAYOVER-MM PIC X(02).                &#xD;
                   15  CSOC229-SCH-DTY-GUAR-TIME.                               &#xD;
                       20  CSOC229-SCH-DTY-GUAR-HRS PIC X(03).                  &#xD;
                       20  CSOC229-SCH-DTY-GUAR-MM PIC X(02).                   &#xD;
                   15  CSOC229-ACT-DTY-GUAR-TIME.                               &#xD;
                       20  CSOC229-ACT-DTY-GUAR-HRS PIC X(03).                  &#xD;
                       20  CSOC229-ACT-DTY-GUAR-MM PIC X(02).                   &#xD;
                   15  CSOC229-SCH-DTY-PAY-TIME.                                &#xD;
                       20  CSOC229-SCH-DTY-PAY-HRS PIC X(03).                   &#xD;
                       20  CSOC229-SCH-DTY-PAY-MM PIC X(02).                    &#xD;
                   15  CSOC229-ACT-DTY-PAY-TIME.                                &#xD;
                       20  CSOC229-ACT-DTY-PAY-HRS PIC X(03).                   &#xD;
                       20  CSOC229-ACT-DTY-PAY-MM PIC X(02).                    &#xD;
                   15  FILLER          PIC X(02).                               &#xD;
                   15  CSOC229-DTY-COMPLETE-IND PIC X(01).                      &#xD;
                   15  CSOC229-DTY-DOM-INTL-IND PIC X(01).                      &#xD;
IL0711             15  CSOC229-DTY-MAND-STRT-SCH-DT PIC X(08).                  &#xD;
IL0711             15  CSOC229-DTY-MAND-STRT-SCH-TM PIC X(04).                  &#xD;
IL0711             15  CSOC229-DTY-MAND-STRT-BAT-DT PIC X(08).                  &#xD;
IL0711             15  CSOC229-DTY-MAND-STRT-BAT-TM PIC X(04).                  &#xD;</copybook>
        <origCopybook>      *                                                                         &#xD;
       01  STC200-SEGMENT-IO-AREA.                                              &#xD;
           05  STC200-MSG-LENGTH       PIC 9(04).                               &#xD;
           05  STC200-MSG.                                                      &#xD;
               10  STC200-MSG-SEQ-NUM  PIC 9(04) VALUE ZERO.                    &#xD;
               10  STC200-MSG-KEY-VALUE.                                        &#xD;
                   15  STC200-MSG-TYPE PIC 9(04).                               &#xD;
                       88  STC200-NEW-PRG-UPDATE        VALUE 5101&#xD;
                   15  STC200-MSG-ID.                                           &#xD;
                       20  STC200-MSG-DATE.                                     &#xD;
                           25  STC200-MSG-YY PIC 9(02).                         &#xD;
                           25  STC200-MSG-MM PIC 9(02).                         &#xD;
                           25  STC200-MSG-DD PIC 9(02).                         &#xD;
                       20  STC200-MSG-TIME.                                     &#xD;
                           25  STC200-MSG-HOURS PIC 9(02).                      &#xD;
                           25  STC200-MSG-MINUTES PIC 9(02).                    &#xD;
                           25  STC200-MSG-SECONDS PIC 9(02).                    &#xD;
                           25  STC200-MSG-DECIMAL PIC X(01) VALUE '.'.          &#xD;
                           25  STC200-MSG-MILLI-SEC PIC 9(03).                  &#xD;
               10  STC200-MSG-SEQ-STUFFER PIC 9(04) VALUE ZERO.                 &#xD;
               10  STC200-MSG-CARRIER-CODE PIC X(03).                           &#xD;
               10  STC200-MSG-PROGRAM-ID PIC X(08).                        &#xD;
&#xD;
       01  CSOC-PAIRING-RECORD-WORK-AREA.                                       &#xD;
           05  CSOC-PAIRING-RECORD-COUNTS.                                      &#xD;
               10  CSOC225-GEN-PRG-COUNT PIC 9(02).                             &#xD;
               10  CSOC226-POS-COUNT   PIC 9(02).                               &#xD;
               10  CSOC227-OVR-COUNT   PIC 9(02).                               &#xD;
               10  CSOC228-LEG-COUNT   PIC 9(02).                               &#xD;
               10  CSOC229-DTY-COUNT   PIC 9(02).                               &#xD;
           05  CSOC225-GENERAL-PAIRING-DATA.                                    &#xD;
               10  CSOC225-ACTION-CODE PIC X(01).                               &#xD;
                   88  CSOC225-ADD VALUE 'A'.                                   &#xD;
                   88  CSOC225-CHANGE VALUE 'C'.                                &#xD;
                   88  CSOC225-DELETE VALUE 'D'.                                &#xD;
               10  CSOC225-PRNG-KEY.                                            &#xD;
                   15  CSOC225-PRNG-CARRIER PIC X(03).                          &#xD;
                   15  CSOC225-PRNG-CLASS PIC X(01).                            &#xD;
                   15  CSOC225-PRNG-NUM PIC X(06).                              &#xD;
                   15  CSOC225-PRNG-DATE PIC X(08).                             &#xD;
               10  CSOC225-PRNG-END-DATE PIC X(08).                             &#xD;
               10  CSOC225-PRNG-STATUS-IND PIC X(01).                           &#xD;
               10  CSOC225-PRNG-CANCEL-IND PIC X(01).                           &#xD;
               10  CSOC225-EFF-FROM-ZULU PIC X(08).                             &#xD;
               10  CSOC225-EFF-TO-ZULU PIC X(08).                               &#xD;
               10  CSOC225-FREQ        PIC X(04).                               &#xD;
               10  CSOC225-DOM-INTL-IND PIC X(01).                              &#xD;
               10  CSOC225-COMMENTS    PIC X(234).                              &#xD;
               10  CSOC225-PAIRING-TOTALS.                                      &#xD;
                   15  CSOC225-SCHED-FLT-TIME.                                  &#xD;
                       20  CSOC225-SCH-FLT-HRS PIC X(03).                       &#xD;
                       20  CSOC225-SCH-FLT-MM PIC X(02).                        &#xD;
                   15  CSOC225-ACTUAL-FLT-TIME.                                 &#xD;
                       20  CSOC225-ACT-FLT-HRS PIC X(03).                       &#xD;
                       20  CSOC225-ACT-FLT-MM PIC X(02).                        &#xD;
                   15  CSOC225-SCHED-DH-TIME.                                   &#xD;
                       20  CSOC225-SCH-DH-HRS PIC X(03).                        &#xD;
                       20  CSOC225-SCH-DH-MM PIC X(02).                         &#xD;
                   15  CSOC225-ACTUAL-DH-TIME.                                  &#xD;
                       20  CSOC225-ACT-DH-HRS PIC X(03).                        &#xD;
                       20  CSOC225-ACT-DH-MM PIC X(02).                         &#xD;
                   15  CSOC225-SCHED-GUAR-TIME.                                 &#xD;
                       20  CSOC225-SCH-GUAR-HRS PIC X(03).                      &#xD;
                       20  CSOC225-SCH-GUAR-MM PIC X(02).                       &#xD;
                   15  CSOC225-ACTUAL-GUAR-TIME.                                &#xD;
                       20  CSOC225-ACT-GUAR-HRS PIC X(03).                      &#xD;
                       20  CSOC225-ACT-GUAR-MM PIC X(02).                       &#xD;
                   15  CSOC225-SCHED-PAY-TIME.                                  &#xD;
                       20  CSOC225-SCH-PAY-HRS PIC X(03).                       &#xD;
                       20  CSOC225-SCH-PAY-MM PIC X(02).                        &#xD;
                   15  CSOC225-ACTUAL-PAY-TIME.                                 &#xD;
                       20  CSOC225-ACT-PAY-HRS PIC X(03).                       &#xD;
                       20  CSOC225-ACT-PAY-MM PIC X(02).                        &#xD;
                   15  CSOC225-SCHED-TAFB.                                      &#xD;
                       20  CSOC225-SCH-TAFB-HRS PIC X(03).                      &#xD;
                       20  CSOC225-SCH-TAFB-MM PIC X(02).                       &#xD;
                   15  CSOC225-ACTUAL-TAFB.                                     &#xD;
                       20  CSOC225-ACT-TAFB-HRS PIC X(03).                      &#xD;
                       20  CSOC225-ACT-TAFB-MM PIC X(02).                       &#xD;
               10  CSOC225-UPDATE-DATA.                                         &#xD;
                   15  CSOC225-UPDATE-EMP-NO PIC X(10).                         &#xD;
                   15  CSOC225-UPDATE-DATE PIC X(08).                           &#xD;
                   15  CSOC225-UPDATE-TIME PIC X(06).                           &#xD;
           05  CSOC226-PAIRING-POS-WORK-AREA.                                   &#xD;
               10  CSOC226-POSITIONS OCCURS 0 TO 24 TIMES                       &#xD;
               DEPENDING ON CSOC226-POS-COUNT INDEXED BY CSOC226-INDEX.         &#xD;
                   15  CSOC226-POS-ASSGN-POS PIC X(04).                         &#xD;
                   15  CSOC226-POS-STATUS PIC X(01).                            &#xD;
                   15  CSOC226-POS-RSRV-IND PIC X(01).                          &#xD;
                   15  CSOC226-POS-EMP-ID PIC X(10).                            &#xD;
                   15  CSOC226-POS-EMP-NAME.                                    &#xD;
                       20  CSOC226-POS-EMP-FIRST-NAME PIC X(15).                &#xD;
                       20  CSOC226-POS-EMP-MID-INIT PIC X(01).                  &#xD;
                       20  CSOC226-POS-EMP-LAST-NAME PIC X(15).                 &#xD;
           05  CSOC227-PAIRING-POS-OVR-AREA.                                    &#xD;
RH1103         10  CSOC227-POS-OVR-DATA OCCURS 0 TO 50 TIMES                    &#xD;
               DEPENDING ON CSOC227-OVR-COUNT INDEXED BY CSOC227-INDEX.         &#xD;
KV9609             15  CSOC227-POS-OVR-ACTION-CODE PIC X(01).                   &#xD;
                   15  CSOC227-POS-OVR-ASSGN-POS PIC X(04).                     &#xD;
                   15  CSOC227-POS-OVR-SEQ-NUM PIC X(03).                       &#xD;
                   15  CSOC227-POS-OVR-POS PIC X(04).                           &#xD;
           05  CSOC228-PAIRING-LEG-AREA.                                        &#xD;
KV1103         10  CSOC228-LEG-DATA OCCURS 0 TO 50 TIMES                        &#xD;
               DEPENDING ON CSOC228-LEG-COUNT INDEXED BY CSOC228-INDEX.         &#xD;
                   15  CSOC228-SEQ-NUM PIC X(03).                               &#xD;
                   15  CSOC228-SCH-DPT-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC228-SCH-DPT-TIME-ZULU PIC X(04).                     &#xD;
                   15  CSOC228-CARRIER PIC X(03).                               &#xD;
                   15  CSOC228-FLT-NUM PIC X(04).                               &#xD;
                   15  CSOC228-DPT-CITY PIC X(03).                              &#xD;
                   15  CSOC228-ARR-CITY PIC X(03).                              &#xD;
                   15  CSOC228-EQUIPMENT-CODE PIC X(03).                        &#xD;
                   15  CSOC228-FLIGHT-LEG-STATUS PIC X(02).                     &#xD;
                   15  CSOC228-ROB-IND PIC X(01).                               &#xD;
                   15  CSOC228-LEG-DOM-INTL-IND PIC X(01).                      &#xD;
                   15  CSOC228-DH-IND  PIC X(01).                               &#xD;
                   15  CSOC228-DH-CARRIER PIC X(03).                            &#xD;
                   15  CSOC228-RECORD-LOCATOR-PNR PIC X(06).                    &#xD;
                   15  CSOC228-SCH-AUG-CNT PIC X(01).                           &#xD;
                   15  CSOC228-ACT-AUG-CNT PIC X(01).                           &#xD;
                   15  CSOC228-SCH-ARR-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC228-SCH-ARR-TIME-ZULU PIC X(04).                     &#xD;
                   15  CSOC228-EST-DPT-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC228-EST-DPT-TIME-ZULU PIC X(04).                     &#xD;
                   15  CSOC228-EST-ARR-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC228-EST-ARR-TIME-ZULU PIC X(04).                     &#xD;
                   15  CSOC228-ACT-DPT-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC228-ACT-DPT-TIME-ZULU PIC X(04).                     &#xD;
                   15  CSOC228-ACT-ARR-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC228-ACT-ARR-TIME-ZULU PIC X(04).                     &#xD;
                   15  CSOC228-TAIL-NUMBER PIC X(04).                           &#xD;
           05  CSOC229-DUTY-AREA.                                               &#xD;
KV1103         10  CSOC229-DUTY-DATA OCCURS 0 TO 20 TIMES                       &#xD;
               DEPENDING ON CSOC229-DTY-COUNT INDEXED BY CSOC229-INDEX.         &#xD;
                   15  CSOC229-DTY-SEQ-NUM PIC X(03).                           &#xD;
                   15  CSOC229-DTY-REST-TYPE-1 PIC X(02).                       &#xD;
                   15  CSOC229-DTY-REST-TYPE-2 PIC X(02).                       &#xD;
                   15  CSOC229-DTY-DUTY-NUM PIC X(04).                          &#xD;
                   15  CSOC229-SCH-RPT-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC229-SCH-BRF-TIME-ZULU PIC X(04).                     &#xD;
                   15  CSOC229-ACT-RPT-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC229-ACT-BRF-TIME-ZULU PIC X(04).                     &#xD;
                   15  CSOC229-SCH-END-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC229-SCH-DBRF-TIME-ZULU PIC X(04).                    &#xD;
                   15  CSOC229-ACT-END-DATE-ZULU PIC X(08).                     &#xD;
                   15  CSOC229-ACT-DBRF-TIME-ZULU PIC X(04).                    &#xD;
                   15  CSOC229-DTY-HTL-CODE PIC X(03).                          &#xD;
                   15  CSOC229-SCH-DTY-AUGMENT-CNT PIC X(01).                   &#xD;
                   15  CSOC229-ACT-DTY-AUGMENT-CNT PIC X(01).                   &#xD;
                   15  CSOC229-SCH-DTY-FLT-TIME.                                &#xD;
                       20  CSOC229-SCH-DTY-FLT-HRS PIC X(03).                   &#xD;
                       20  CSOC229-SCH-DTY-FLT-MM PIC X(02).                    &#xD;
                   15  CSOC229-ACT-DTY-FLT-TIME.                                &#xD;
                       20  CSOC229-ACT-DTY-FLT-HRS PIC X(03).                   &#xD;
                       20  CSOC229-ACT-DTY-FLT-MM PIC X(02).                    &#xD;
                   15  CSOC229-SCH-DTY-DUTY-TIME.                               &#xD;
                       20  CSOC229-SCH-DTY-DUTY-HRS PIC X(03).                  &#xD;
                       20  CSOC229-SCH-DTY-DUTY-MM PIC X(02).                   &#xD;
                   15  CSOC229-ACT-DTY-DUTY-TIME.                               &#xD;
                       20  CSOC229-ACT-DTY-DUTY-HRS PIC X(03).                  &#xD;
                       20  CSOC229-ACT-DTY-DUTY-MM PIC X(02).                   &#xD;
                   15  CSOC229-SCH-DTY-LAYOVER-TIME.                            &#xD;
                       20  CSOC229-SCH-DTY-LAYOVER-HRS PIC X(03).               &#xD;
                       20  CSOC229-SCH-DTY-LAYOVER-MM PIC X(02).                &#xD;
                   15  CSOC229-ACT-DTY-LAYOVER-TIME.                            &#xD;
                       20  CSOC229-ACT-DTY-LAYOVER-HRS PIC X(03).               &#xD;
                       20  CSOC229-ACT-DTY-LAYOVER-MM PIC X(02).                &#xD;
                   15  CSOC229-SCH-DTY-GUAR-TIME.                               &#xD;
                       20  CSOC229-SCH-DTY-GUAR-HRS PIC X(03).                  &#xD;
                       20  CSOC229-SCH-DTY-GUAR-MM PIC X(02).                   &#xD;
                   15  CSOC229-ACT-DTY-GUAR-TIME.                               &#xD;
                       20  CSOC229-ACT-DTY-GUAR-HRS PIC X(03).                  &#xD;
                       20  CSOC229-ACT-DTY-GUAR-MM PIC X(02).                   &#xD;
                   15  CSOC229-SCH-DTY-PAY-TIME.                                &#xD;
                       20  CSOC229-SCH-DTY-PAY-HRS PIC X(03).                   &#xD;
                       20  CSOC229-SCH-DTY-PAY-MM PIC X(02).                    &#xD;
                   15  CSOC229-ACT-DTY-PAY-TIME.                                &#xD;
                       20  CSOC229-ACT-DTY-PAY-HRS PIC X(03).                   &#xD;
                       20  CSOC229-ACT-DTY-PAY-MM PIC X(02).                    &#xD;
                   15  FILLER          PIC X(02).                               &#xD;
                   15  CSOC229-DTY-COMPLETE-IND PIC X(01).                      &#xD;
                   15  CSOC229-DTY-DOM-INTL-IND PIC X(01).                      &#xD;
IL0711             15  CSOC229-DTY-MAND-STRT-SCH-DT PIC X(08).                  &#xD;
IL0711             15  CSOC229-DTY-MAND-STRT-SCH-TM PIC X(04).                  &#xD;
IL0711             15  CSOC229-DTY-MAND-STRT-BAT-DT PIC X(08).                  &#xD;
IL0711             15  CSOC229-DTY-MAND-STRT-BAT-TM PIC X(04).                  &#xD;
</origCopybook>
        <truncBin>false</truncBin>
        <redefineGroups/>
    </config>
</BWSharedResource>